[package]
name = "t-pipe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unescaper = "0.1.2"
serde_json = "1.0.107"
serde = { version = "1.0.189", features = ["derive"] }